#!/usr/bin/env python

import sys
import logging
import requests
import datetime

if __name__ == "__main__":

    latest_spec = "https://raw.githubusercontent.com/whosonfirst/whosonfirst-placetypes/master/data/placetypes-spec-latest.json"

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-s', '--spec', dest='spec', action='store', default=latest_spec, help='Where to fetch specification data from')

    options, args = opt_parser.parse_args()    
    
    body = None

    if options.spec.startswith("file://"):

        path = options.spec.replace("file://", "")
        fh = open(path, "r")

        body = fh.read()
        fh.close()

    else:
        rsp = requests.get(options.spec)

        if rsp.status_code != 200:
            logging.error("Failed to GET %s" % options.spec)
            sys.exit(1)

        body = rsp.content

    if body == None:
        logging.error("Body is null")
        sys.exit(1)

    now = datetime.datetime.utcnow().isoformat()
    
    fh = sys.stdout
    
    fh.write("# %s\n" % options.spec)
    fh.write("# This file was generated by robots (%s) at %s\n\n" % ("utils/mk-spec.py", now))
    fh.write("__SPEC__ = %s" % body)
        
    sys.exit(0)
    
